### ISSUE TITLE
Find pods with high restart count

### ISSUE THREAD

**Issue by milsonian** [k8guard/k8guard-discover#16]
Identifying pods (and ancestors) with high restart counts/churn would be useful for consumers and help eliminate wasted resources - this often occurs with forgotten experiments, broken apps, and suboptimal job behavior (e.g. uncontrollable restart behavior with non-zero exits).

**Comment by medyagh** [comment]
Great idea ! will need to introduce a new type of violation, which should be straight forward, also need to see if client-go api gives us that information, what do you think @rmb938 ?
