### ISSUE TITLE
custom plugins

### ISSUE THREAD

**Issue by joshkurz** [k8guard/k8guard-discover#32]
Not all requirements should be in core. Is there a plugin methodology for this application? I didn't see one in the docs, so if I missed it, my bad. 

I can see a very real use case for being able to simply write a custom requirement and have k8sguard do it's normal thing except with user defined functions.

**Comment by medyagh** [comment]
@joshkurz that is actually one of the ideas we like to see it implemented, maybe a plugin system with Lua or something like that?
