### ISSUE TITLE
duplicate ingress

### ISSUE THREAD

**Issue by rmb938** [k8guard/k8guard-discover#8]
Discover when there are overlapping ingress hosts

**Comment by medyagh** [comment]
@rmb938 I was this close to label your feature-request as Duplicate ;) great suggestion for a feature!

**Comment by brianberzins** [comment]
I just got burned by this with an example application. Two forks, different namespaces, didn't change the ingress paths. Ended up killing all of my functional tests. If I weren't able to see all namespaces (admin) that could have been a real nightmare to figure out.

👍
